services:
  db:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
  
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
      - availability-service
      - notification-service
      - sala-service
    networks:
      - mynetwork

  auth-service:
    container_name: auth-service
    build: ./services/auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    depends_on:
      - db
      - user-service
    networks:
      - mynetwork

  user-service:
    container_name: user-service
    build: ./services/user-service
    ports:
      - "3002:3002"
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - mynetwork

  notification-service:
    container_name: notification-service
    build: ./services/notification-service
    ports:
      - "3005:3005"
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - mynetwork
      
  availability-service:
    container_name: availability-service
    build: ./services/availability-service
    ports:
      - "3006:3006"
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - mynetwork


  reservation-service:
    container_name: reservation-service
    build: ./services/reservation-service
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - mynetwork

  # Serviço de Salas (Sala Service)
  sala-service:
    container_name: sala-service
    build: ./services/sala-service  # Caminho para o diretório onde seu serviço sala-service está localizado
    ports:
      - "3004:3004"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres  # URL de conexão com o banco de dados
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: